name: Issue Creation Tracker
on:
  discussion:
    types: [created]
  discussion_comment:
    types: [created]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git Issue Details
      run: |
          echo "Issue creator: ${{ toJson(github.event) }}"
          echo "Issue title: ${{ github.event.discussion.title }}"
          echo "Issue number: ${{ github.event.discussion.html_url }}"
    - name: Google Chat Notification
      run: |
          curl --location --request POST '${{ secrets.WEBHOOK }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "cards": [
                  {
                      "header": {
                          "title": "${{ github.event.discussion.title }}",
                          "URL": "${{ github.event.discussion.comment.html_url }}"
                      },
                      "sections": [
                          {
                              "widgets": [
                                   {
                                      "buttons": [
                                          {
                                              "textButton": {
                                                  "text": "OPEN DISCUSSION",
                                                  "onClick": {
                                                      "openLink": {
                                                          "url": "${{ github.event.discussion.comment.html_url }}"
                                                      }
                                                  }
                                              }
                                          }
                                      ]
                                  }
                              ]
                          }
                      ]
                  }
              ]
          }'
