name: Issue Creation Tracker
on:
  discussion:
    types: [created]
  discussion_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git Disc. created
      if: github.event.discussion && !github.event.comment
      run: |
          curl --location --request POST '${{ secrets.WEBHOOK }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "cards": [
                  {
                      "header": {
                          "title": "${{ github.event.discussion.title }}",
                          "subtitle": "${{ github.event.user.login }}によって新しいトピックが作られました"
                      },
                      "sections": [
                          {
                              "widgets": [
                                   {
                                      "buttons": [
                                          {
                                              "textButton": {
                                                  "text": "OPEN DISCUSSION",
                                                  "onClick": {
                                                      "openLink": {
                                                          "url": "${{ github.event.discussion.html_url }}"
                                                      }
                                                  }
                                              }
                                          }
                                      ]
                                  }
                              ]
                          }
                      ]
                  }
              ]
          }'
          
    - name: Git Disc. commented
      if: github.event.discussion && github.event.comment
      run: |
          curl --location --request POST '${{ secrets.WEBHOOK }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "cards": [
                  {
                      "header": {
                          "title": "${{ github.event.discussion.title }}",
                          "subtitle": "${{ github.event.comment.user.login }}がコメントしました"
                      },
                      "sections": [
                          {
                              "widgets": [
                                   {
                                      "buttons": [
                                          {
                                              "textButton": {
                                                  "text": "OPEN DISCUSSION",
                                                  "onClick": {
                                                      "openLink": {
                                                          "url": "${{ github.event.comment.html_url }}"
                                                      }
                                                  }
                                              }
                                          }
                                      ]
                                  }
                              ]
                          }
                      ]
                  }
              ]
          }'
