name: Discussions Creation Tracker
on:
  discussion:
    types: [created]
  discussion_comment:
    types: [created]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git Issue Details
      run: |
          echo "Issue creator: ${{ github.event.discussion }}"
    - name: Google Chat Notification
      run: |
          curl --location --request POST '${{ secrets.WEBHOOK }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
            '{ "text": "Created discussion: ${{ github.event.discussion.html_url }}" }' ${{ secrets.GOOGLECHAT_WEBHOOK_URL }}
          }'
