name: Discussions Creation Tracker
on:
  discussion:
    types: [created]
  discussion_comment:
    types: [created]
    
jobs:
  discussion_created:
    runs-on: ubuntu-latest
    if: github.event.discussion && !github.event.comment
    steps:
      - run: |
          echo "Issue creator: ${{ toJson(github.event) }}"
          curl --location --request POST '${{ secrets.WEBHOOK }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "cards": [
                  {
                      "header": {
                          "title": "#${{ github.event.discussion.title  }}",
                          # "subtitle": "Issue No: #${{ toJson(github.event.discussion)  }}"
                          "URL": "${{ github.event.discussion.html_url }}"
                      },
                  }
              ]
          }'
  discussion_commented:
    runs-on: ubuntu-latest
    if: github.event.discussion && github.event.comment
    steps:
      - run: |
          echo "Issue creator: ${{ toJson(github.event) }}"
          curl --location --request POST '${{ secrets.WEBHOOK }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "cards": [
                  {
                      "header": {
                          "title": "#${{ github.event.discussion.title  }}",
                          # "subtitle": "Issue No: #${{ toJson(github.event.discussion)  }}"
                          "URL": "${{ github.event.discussion.comment.html_url }}"
                      },
                  }
              ]
          }'
