name: Discussions Creation Tracker
on:
  discussion:
    types: [created]
  discussion_comment:
    types: [created]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git Issue Details
      run: |
          echo "Issue creator: ${{ toJson(github.event.discussion) }}"
    - name: Google Chat Notification
      run: |
          curl --location --request POST '${{ secrets.WEBHOOK }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "cards": [
                  {
                      "header": {
                          "title": "Issue Tracker",
                          "subtitle": "Issue No: #${{ toJson(github.event.discussion)  }}"
                      },
                  }
              ]
          }'
